allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@tailwindcss/oxide': true
  esbuild: true
  msgpackr-extract: true
  prisma: set this to true or false
  sharp: true
  unrs-resolver: true
